version: '2'
services:
  back:
    build: .
    volumes:
      - ./:/go/src/github.com/johnsudaar/acp
    environment:
      DATABASE_URL: "mongodb://mongo:27017/acp"
      SERVER_PORT: 8081
    ports:
      - 8081:8081
      - 9090:9090
      - 9091:9091
      - 9993:9993
    links:
      - mongo
    command: reflex -r '\.go$$' -s -- sh -c 'go build && ./acp --no-gui'
  front:
    image: node:16
    volumes:
      - ./front/:/mnt
    ports:
      - 8080:8080
    working_dir: /mnt
    command: bash -c "yarn && yarn serve"
  docs:
    image: slatedocs/slate
    volumes:
      - ./docs:/srv/slate/source
    ports:
      - 4567:4567
    command: serve
  mongo:
    image: mongo
    volumes:
      - ./docker/data:/data/db
    ports:
      - 27019:27017


